version: "3"

networks:
  grafana:

volumes:
  postgres: {}
  grafana: {}

services:
  timescaledb:
    image: timescale/timescaledb-postgis:2.0.0-pg12
    container_name: timescaledb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - grafana

  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - grafana
