{
 "title": "Taxi Dashboard",
 "time": { "from": "2015-12-31T23:00:00.000Z", "to": "2016-01-07T22:59:59.000Z" },
 "panels": [
  {
   "title": "First Count",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30 minutes', pickup_datetime) AS time, COUNT(*) AS near_times_sq\nFROM rides\nWHERE ST_Distance(pickup_geom, ST_Transform(ST_SetSRID(ST_MakePoint(-73.9851,40.7589),4326),2163)) < 400\nAND pickup_datetime < '2016-01-07 23:59'\nGROUP BY time ORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Last Count",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30 minutes', pickup_datetime) AS time, COUNT(*) AS near_times_sq\nFROM rides\nWHERE ST_Distance(pickup_geom, ST_Transform(ST_SetSRID(ST_MakePoint(-73.9851,40.7589),4326),2163)) < 400\nAND pickup_datetime < '2016-01-07 23:59'\nGROUP BY time ORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Average Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30 minutes', pickup_datetime) AS time, COUNT(*) AS near_times_sq\nFROM rides\nWHERE ST_Distance(pickup_geom, ST_Transform(ST_SetSRID(ST_MakePoint(-73.9851,40.7589),4326),2163)) < 400\nAND pickup_datetime < '2016-01-07 23:59'\nGROUP BY time ORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Taxi Pick Up Rides near Times Square (30m)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30 minutes', pickup_datetime) AS time, COUNT(*) AS near_times_sq\nFROM rides\nWHERE ST_Distance(pickup_geom, ST_Transform(ST_SetSRID(ST_MakePoint(-73.9851,40.7589),4326),2163)) < 400\nAND pickup_datetime < '2016-01-07 23:59'\nGROUP BY time ORDER BY time;\n\n"
    }
   ]
  },
  {
   "title": "Heatmap of Distance to Time Square",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT pickup_datetime AS time, ST_Distance(pickup_geom, ST_Transform(ST_SetSRID(ST_MakePoint(-73.9851,40.7589),4326),2163)) as distance\nFROM rides\nWHERE ST_Distance(pickup_geom, ST_Transform(ST_SetSRID(ST_MakePoint(-73.9851,40.7589),4326),2163)) < 400\nAND pickup_datetime < '2016-01-07 23:59'\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Payment Types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('30 minutes', pickup_datetime) AS time, description AS metric,\n  COUNT(*) AS n\nFROM rides JOIN payment_types USING(payment_type)\nWHERE pickup_datetime < '2016-01-07 23:59'\nGROUP BY description, time ORDER BY time;\n"
    }
   ]
  }
 ]
}